### ISSUE TITLE
`NoneType` object has no attribute `to`

### ISSUE THREAD

**Issue by lynnporu** [qiang2100/BERT-LS#11]
I've just downloaded the repo, installed all the dependencies and tried to run `./run_LSBert1.sh`. This is the error I got:

```
AttributeError: 'NoneType' object has no attribute 'to' 
```

<details>
<summary>
Full log
</summary>

```
(XXXXXXX) XXXXX@XXXXXX:XXXXXX$ ./run_LSBert1.sh                                                                                             
INFO:__main__:device: cpu n_gpu: 0, distributed training: False, 16-bits training: False                    
INFO:pytorch_pretrained_bert.file_utils:https://s3.amazonaws.com/models.huggingface.co/bert/bert-large-uncased-whole-word-masking-vocab.txt not found in cache, downloading to /tmp/tmppn72yug9                         
100%|█████████████████████████████████████████████████████████████| 231508/231508 [00:03<00:00, 61222.48B/s]INFO:pytorch_pretrained_bert.file_utils:copying /tmp/tmppn72yug9 to cache at /XXXXXXXXXXXX/.cache/torch/pytorch_pretrained_bert/b3a6b2c6d7ea2ffa06d0e7577c1e88b94fad470ae0f060a4ffef3fe0bdf86730.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084                                                                   
INFO:pytorch_pretrained_bert.file_utils:creating metadata file for /XXXXXXXXXXXX/.cache/torch/pytorch_pretrained_bert/b3a6b2c6d7ea2ffa06d0e7577c1e88b94fad470ae0f060a4ffef3fe0bdf86730.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084                                                                             
INFO:pytorch_pretrained_bert.file_utils:removing temp file /tmp/tmppn72yug9                                 
INFO:pytorch_pretrained_bert.tokenization:loading vocabulary file https://s3.amazonaws.com/models.huggingface.co/bert/bert-large-uncased-whole-word-masking-vocab.txt from cache at /XXXXXXXXXXXX/.cache/torch/pytorch_pretrained_bert/b3a6b2c6d7ea2ffa06d0e7577c1e88b94fad470ae0f060a4ffef3fe0bdf86730.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084                                                                        
ERROR:pytorch_pretrained_bert.modeling:Couldn't reach server at '/home/qiang/Desktop/pytorch-pretrained-BERT/bert-large-uncased-whole-word-masking-pytorch_model.bin' to download pretrained weights.                   
Traceback (most recent call last):                                                                          
  File "/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/LSBert1.py", line 951, in <module>            
    main()                                                                                                  
  File "/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/LSBert1.py", line 822, in main                
    model.to(device)                                                                                        
AttributeError: 'NoneType' object has no attribute 'to'  
```

<details>

**Comment by lynnporu** [comment]
It is very weird that the code is trying to access `/home/qiang/Desktop/...`
